### ISSUE TITLE
Deno compile issue "exports is not defined"

### ISSUE THREAD

**Issue by patoui** [deligenius/view-engine#33]
Description
----
When adding view engine and trying to compile, it causes an error

```
error: ReferenceError: exports is not defined
    at file://$deno$/bundle.js:20088:32
```

Deno version details

```
deno 1.17.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

#### Steps to reproduce:

1. create `main.ts`
```typescript
import { Application } from "https://deno.land/x/oak@v10.1.0/mod.ts";
import {
  adapterFactory,
  engineFactory,
  viewEngine,
} from "https://deno.land/x/view_engine@v1.5.0/mod.ts";

const app = new Application();

const ejsEngine = engineFactory.getEjsEngine();
const oakAdapter = adapterFactory.getOakAdapter();

app.use(viewEngine(oakAdapter, ejsEngine));

app.use((ctx) => {
  ctx.response.body = "Hello world!";
});

await app.listen({ port: 8000 });
```

2. run `deno compile -A -o main main.ts`
3. run binary `./main`

You should see the follow output (or similar):
```
error: ReferenceError: exports is not defined
    at file://$deno$/bundle.js:20088:32
```

**Comment by gjuoun** [comment]
Please use the newest version, Thanks!
